name: CI - Ejecutar y validar aplicación

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias (si las hubiera)
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Verificar estilo con flake8
        run: |
          flake8 main.py estudiantes/

      - name: Ejecutar aplicación
        run: |
          python main.py